### PR TITLE
Migrate to Spring Boot 3

### PR DESCRIPTION
**Pull request by jpoge2**
Hi Marc!
WDYT about migrating to spring boot 3? It would be nice to be able to use this wonderful starter in the new version of framework :)

xoxo, jpoge2

### CODE REVIEW

**Comment by jpoge2** [comment]
these issues were already present in the code ;d

**Comment by t-oster** [comment]
Hi, @MarcGiffing is the spring-boot 3 release planned anytime soon? I am depending on this for a project which needs to migrate to spring boot 3.

**Comment by t-oster** [comment]
Wow that was quick. Thank you.

**Comment by MarcGiffing** [comment]
Please try Version 0.9.0-RC1. It will be available in a in a couple hours. Thank you [jpoge2](https://github.com/jpoge2)!

**Comment by t-oster** [comment]
Works, thank you

**Pull request merged**
